name = "StochasticIntegrators"
uuid = "62159e39-8b8b-4adf-9c3e-8dd1da10d3ac"
version = "0.3.1"
authors = ["Michael Kraus <michael.kraus@ipp.mpg.de>", "Tomasz M. Tyranowski <tomasz.tyranowski@ipp.mpg.de>"]

[deps]
GeometricBase = "9a0b12b7-583b-4f04-aa1f-d8551b6addc9"
GeometricEquations = "c85262ba-a08a-430a-b926-d29770767bf2"
GeometricIntegratorsBase = "71212ab4-08a2-48eb-a02b-4cbad0e9c44a"
GeometricSolutions = "7843afe4-64f4-4df4-9231-049495c56661"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RungeKutta = "fb486d5c-30a0-4a8a-8415-a8b4ace5a6f7"
SimpleSolvers = "36b790f5-6434-4fbe-b711-1f64a1e2f6a2"

[compat]
GeometricBase = "0.15.0"
GeometricEquations = "0.21.5"
GeometricIntegratorsBase = "0.6.9"
GeometricSolutions = "0.6.6"
LinearAlgebra = "1"
Random = "1"
Reexport = "1"
RungeKutta = "0.6.4"
SimpleSolvers = "0.14.1"
julia = "1.11"
